Repository scverse/squidpy, pull requests merged in 2022-02, with the labels that each got.

#453 Fixes napari slider and contrast limits
  docs/source/conf.py
  setup.py
  squidpy/pl/_interactive/_controller.py
  tox.ini
Labels: bugfix

#463 Explicitly check for None in complex policy
  squidpy/gr/_ligrec.py
Labels: ignore-towncrier, bugfix

#432 Add intervals argument to sq.gr.co_occurrence
  .pre-commit-config.yaml
  squidpy/gr/_ppatterns.py
  tests/graph/test_ppatterns.py
Labels: feature
