Repository scverse/squidpy, pull requests merged in 2022-06, with the labels that each got.

#561 Fix plotting non-unique categorical colors
  docs/source/installation.rst
  setup.py
  squidpy/im/_container.py
  squidpy/pl/_color_utils.py
  squidpy/pl/_spatial_utils.py
  tests/_images/SpatialStatic_spatial_scatter_non_unique_colors.png
  tests/plotting/test_spatial_static.py
Labels: bugfix

#562 better error message for palette
  squidpy/pl/_color_utils.py
Labels: misc

#573 fix release notes
  docs/source/release/changelog/568.bugfix.rst
  docs/source/release/changelog/569.doc.rst
  docs/source/release/notes-1.2.2.rst
  docs/source/release/notes-dev.rst
Labels: ignore-towncrier

#567 fix nanostring fov file
  squidpy/read/_read.py
Labels: bugfix
