Repository scverse/squidpy, pull requests merged in 2022-03, with the labels that each got.

#473 Misc/remove dev
  .github/.codecov.yml
  .github/workflows/deployment.yml
  .github/workflows/news.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/source/conf.py
  docs/source/utils.py
  squidpy/_utils.py
  squidpy/gr/_ligrec.py
  squidpy/gr/_ppatterns.py
  squidpy/gr/_sepal.py
  squidpy/im/_container.py
  squidpy/im/_coords.py
  squidpy/im/_feature_mixin.py
  squidpy/im/_segment.py
  squidpy/pl/_interactive/_controller.py
  squidpy/pl/_ligrec.py
  tests/image/test_container.py
  tox.ini
Labels: misc

#474 Merge dev into master
  .github/.codecov.yml
  .github/workflows/deployment.yml
  .github/workflows/news.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.rst
  README_pypi.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/references.bib
  docs/source/release/changelog/420.bugfix.rst
  docs/source/release/changelog/434.bugfix.rst
  docs/source/release/notes-dev.rst
  docs/source/utils.py
  requirements.txt
  setup.py
  squidpy/__init__.py
  squidpy/_utils.py
  squidpy/gr/_build.py
  squidpy/gr/_ligrec.py
  squidpy/gr/_ppatterns.py
  squidpy/gr/_sepal.py
  squidpy/gr/_utils.py
  squidpy/im/_container.py
  squidpy/im/_coords.py
  squidpy/im/_feature_mixin.py
  squidpy/im/_segment.py
  squidpy/pl/_interactive/_controller.py
  squidpy/pl/_ligrec.py
  tests/_images/Graph_interaction_dendro.png
  tests/_images/Graph_nhood_enrichment_dendro.png
  tests/datasets/test_dataset.py
  tests/graph/test_ligrec.py
  tests/graph/test_ppatterns.py
  tests/image/test_container.py
  tox.ini
Labels: ignore-towncrier

#477 Fix grammar in docs
  README.rst
  README_pypi.rst
  docs/source/index.rst
Labels: ignore-towncrier, doc

#480 Add type stubs to datasets
  .pre-commit-config.yaml
  squidpy/datasets/_dataset.pyi
  squidpy/datasets/_image.pyi
Labels: misc

#488 Fix/napari 0.4.15
  setup.py
  squidpy/im/_segment.py
  squidpy/pl/_interactive/_controller.py
Labels: bugfix

#489 Fix/warnings
  requirements.txt
  setup.py
  squidpy/gr/_ligrec.py
  squidpy/gr/_nhood.py
  squidpy/im/_container.py
  squidpy/im/_feature_mixin.py
  squidpy/im/_process.py
  squidpy/pl/_graph.py
  squidpy/pl/_ligrec.py
  tests/_data/test_data.h5ad
  tests/conftest.py
  tests/datasets/test_dataset.py
  tests/image/test_container.py
  tests/image/test_io.py
  tox.ini
Labels: misc

#493 Add ax keyword to nhood enrichment plot
  squidpy/_docs.py
  squidpy/pl/_graph.py
  squidpy/pl/_utils.py
  tests/_images/Graph_nhood_enrichment_ax.png
  tests/plotting/test_graph.py
Labels: feature

#494 Feature/towncrier news author
  .github/workflows/news.yml
  CONTRIBUTING.rst
  docs/source/create_news_fragment.py
  docs/source/release/changelog/493.feature.rst
  docs/source/release/notes-dev.rst
Labels: doc
