Repository scverse/squidpy, pull requests merged in 2022-04, with the labels that each got.

#506 Fix/spatial autocorr raw
  .pre-commit-config.yaml
  docs/source/utils.py
  squidpy/_constants/_utils.py
  squidpy/gr/_ppatterns.py
  tests/graph/test_ppatterns.py
Labels: bugfix

#508 Check dims for backwards compatibility of image loading
  squidpy/im/_container.py
Labels: bugfix

#509 Fix missing Z-dim
  squidpy/im/_container.py
  tests/image/test_container.py
Labels: bugfix

#510 Fix typo in save_fig: Path -> path
  squidpy/pl/_utils.py
Labels: bugfix

#514 Make `spot_diameter` more flexible
  squidpy/_constants/_pkg_constants.py
  squidpy/im/_container.py
  squidpy/pl/_interactive/_model.py
  tests/image/test_container.py
Labels: feature

#515 Add warning to clarify usage of `spatial_neighbors`
  squidpy/gr/_build.py
Labels: misc

#449 Visium datasets in Squidpy
  docs/source/api.rst
  docs/source/spelling_wordlist.txt
  squidpy/_constants/_constants.py
  squidpy/datasets/_10x_datasets.py
  squidpy/datasets/__init__.py
  tests/datasets/test_download_visium_dataset.py
Labels: feature

#468 Read_visium
  docs/source/api.rst
  docs/source/utils.py
  squidpy/__init__.py
  squidpy/_constants/_pkg_constants.py
  squidpy/datasets/_10x_datasets.py
  squidpy/read/__init__.py
  squidpy/read/_read.py
  squidpy/read/_utils.py
  tests/_data/filtered_feature_bc_matrix.h5
  tests/_data/spatial/scalefactors_json.json
  tests/_data/spatial/tissue_hires_image.png
  tests/_data/spatial/tissue_lowres_image.png
  tests/_data/spatial/tissue_positions_list.csv
  tests/read/__init__.py
  tests/read/test_visium.py
  tox.ini
Labels: feature

#516 add multislice graph building
  squidpy/_docs.py
  squidpy/gr/_build.py
  tests/graph/test_spatial_neighbors.py
Labels: feature

#500 Remote zarr image container
  requirements.txt
  squidpy/im/_container.py
  tests/image/test_container.py
Labels: feature

#437 static plotting for spatial data
  .github/workflows/test.yml
  .gitignore
  .mypy.ini
  .pre-commit-config.yaml
  .scripts/ci/download_data.py
  CONTRIBUTING.rst
  docs/source/api.rst
  docs/source/spelling_wordlist.txt
  requirements.txt
  squidpy/_constants/_constants.py
  squidpy/_constants/_pkg_constants.py
  squidpy/_docs.py
  squidpy/im/_container.py
  squidpy/im/_process.py
  squidpy/pl/__init__.py
  squidpy/pl/_color_utils.py
  squidpy/pl/_graph.py
  squidpy/pl/_ligrec.py
  squidpy/pl/_spatial.py
  squidpy/pl/_spatial_utils.py
  squidpy/pl/_utils.py
  squidpy/read/_read.py
  tests/_images/SpatialStatic_spatial_scatter_axfig.png
  tests/_images/SpatialStatic_spatial_scatter_crop.png
  tests/_images/SpatialStatic_spatial_scatter_crop_graph.png
  tests/_images/SpatialStatic_spatial_scatter_crop_noorigin.png
  tests/_images/SpatialStatic_spatial_scatter_group.png
  tests/_images/SpatialStatic_spatial_scatter_group_multi.png
  tests/_images/SpatialStatic_spatial_scatter_group_outline.png
  tests/_images/SpatialStatic_spatial_scatter_image.png
  tests/_images/SpatialStatic_spatial_scatter_noimage.png
  tests/_images/SpatialStatic_spatial_scatter_nospatial.png
  tests/_images/SpatialStatic_spatial_scatter_novisium.png
  tests/_images/SpatialStatic_spatial_scatter_title_single.png
  tests/_images/SpatialStatic_spatial_segment.png
  tests/_images/SpatialStatic_spatial_segment_crop.png
  tests/_images/SpatialStatic_spatial_segment_group.png
  tests/conftest.py
  tests/plotting/test_spatial_static.py
  tox.ini
Labels: feature

#520 add release notes fragments missing
  CONTRIBUTING.rst
  docs/source/release/changelog/420.bugfix.rst
  docs/source/release/changelog/434.bugfix.rst
  docs/source/release/changelog/479.misc.rst
  docs/source/release/changelog/488.bugfix.rst
  docs/source/release/changelog/489.misc.rst
  docs/source/release/changelog/506.bugfix.rst
  docs/source/release/notes-dev.rst
Labels: misc

#521 Generalize img_channel in plotting
  squidpy/pl/_spatial.py
  squidpy/pl/_spatial_utils.py
Labels: ignore-towncrier

#531 Fix adata subset in ImageContainer
  squidpy/_constants/_pkg_constants.py
  squidpy/im/_container.py
  squidpy/pl/_interactive/_model.py
Labels: bugfix

#534 Refactor subsetting
  squidpy/im/_container.py
  squidpy/pl/_interactive/_model.py
Labels: enhancement :sparkles:
